### ISSUE TITLE
Wait for TextEditor's to attach

### ISSUE THREAD

**Issue by Arcanemagus** [mehcode/atom-minimap-plus#6]
It seems that part of the TextEditor rewrite included a change where TextEditors partially initialize _before_ they are attached to the DOM of the main Atom window.

The problem with this is they are initialized enough that `minimap-plus` is attempting to plug into it, but anything that tries to grab screen positions fails as the TextEditor isn't on the screen yet.

An example stack trace of this issue is:
```
Uncaught TypeError: Invalid Point: (NaN, 0)
    at Function.module.exports.Point.assertValid (C:\Users\Landon Abney\AppData\Local\atom\app-1.19.0-beta3\resources\app\node_modules\text-buffer\lib\point.js:63:21)
    at DisplayLayer.translateScreenPosition (C:\Users\Landon Abney\AppData\Local\atom\app-1.19.0-beta3\resources\app\node_modules\text-buffer\lib\display-layer.js:333:17)
    at DisplayLayer.clipScreenPosition (C:\Users\Landon Abney\AppData\Local\atom\app-1.19.0-beta3\resources\app\node_modules\text-buffer\lib\display-layer.js:391:18)
    at TextEditor.module.exports.TextEditor.clipScreenPosition (C:\Users\Landon Abney\AppData\Local\atom\app-1.19.0-beta3\resources\app\src\text-editor.js:1793:38)
    at HTMLElement.pixelPositionForScreenPosition (C:\Users\Landon Abney\AppData\Local\atom\app-1.19.0-beta3\resources\app\src\text-editor-element.js:242:38)
    at StableAdapter.computeScrollTop (C:\Users\Landon Abney\.atom.test\packages\minimap-plus\lib\adapters\stable-adapter.js:60:42)
    at StableAdapter.getScrollTop (C:\Users\Landon Abney\.atom.test\packages\minimap-plus\lib\adapters\stable-adapter.js:51:17)
    at Minimap.getTextEditorScrollRatio (C:\Users\Landon Abney\.atom.test\packages\minimap-plus\lib\minimap.js:598:25)
    at Minimap.getCapedTextEditorScrollRatio (C:\Users\Landon Abney\.atom.test\packages\minimap-plus\lib\minimap.js:610:29)
    at Minimap.getScrollTopFromEditor (C:\Users\Landon Abney\.atom.test\packages\minimap-plus\lib\minimap.js:933:12)
    at Minimap.getScrollTop (C:\Users\Landon Abney\.atom.test\packages\minimap-plus\lib\minimap.js:887:14)
    at Minimap.getLastVisibleScreenRow (C:\Users\Landon Abney\.atom.test\packages\minimap-plus\lib\minimap.js:865:13)
    at Minimap.emitRangeChanges (C:\Users\Landon Abney\.atom.test\packages\minimap-plus\lib\mixins\decoration-management.js:503:38)
    at Minimap.emitDecorationChanges (C:\Users\Landon Abney\.atom.test\packages\minimap-plus\lib\mixins\decoration-management.js:488:10)
    at Minimap.decorateMarker (C:\Users\Landon Abney\.atom.test\packages\minimap-plus\lib\mixins\decoration-management.js:418:10)
    at MinimapLinterBinding.decorateMarker (file:///C:/Users/Landon Abney/Documents/GitHub/atom-minimap-linter/lib/minimap-linter-binding.js:82:50)
    at MinimapLinterBinding.addMessage (file:///C:/Users/Landon Abney/Documents/GitHub/atom-minimap-linter/lib/minimap-linter-binding.js:45:10)
    at file:///C:/Users/Landon Abney/Documents/GitHub/atom-minimap-linter/lib/minimap-linter-binding.js:35:16
    at Set.forEach (native)
    at new MinimapLinterBinding (file:///C:/Users/Landon Abney/Documents/GitHub/atom-minimap-linter/lib/minimap-linter-binding.js:33:21)
    at file:///C:/Users/Landon Abney/Documents/GitHub/atom-minimap-linter/lib/minimap-linter.js:78:23
    at onDidCreateMinimap (C:\Users\Landon Abney\.atom.test\packages\minimap-plus\lib\main.js:379:51)
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\Landon Abney\AppData\Local\atom\app-1.19.0-beta3\resources\app\node_modules\event-kit\lib\emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (C:\Users\Landon Abney\AppData\Local\atom\app-1.19.0-beta3\resources\app\node_modules\event-kit\lib\emitter.js:141:34)
    at subscriptions.add.atom.workspace.observeTextEditors (C:\Users\Landon Abney\.atom.test\packages\minimap-plus\lib\main.js:392:20)
    at C:\Users\Landon Abney\AppData\Local\atom\app-1.19.0-beta3\resources\app\src\workspace.js:721:22
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\Landon Abney\AppData\Local\atom\app-1.19.0-beta3\resources\app\node_modules\event-kit\lib\emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (C:\Users\Landon Abney\AppData\Local\atom\app-1.19.0-beta3\resources\app\node_modules\event-kit\lib\emitter.js:141:34)
    at C:\Users\Landon Abney\AppData\Local\atom\app-1.19.0-beta3\resources\app\src\workspace.js:594:34
    at C:\Users\Landon Abney\AppData\Local\atom\app-1.19.0-beta3\resources\app\src\workspace.js:595:19
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\Landon Abney\AppData\Local\atom\app-1.19.0-beta3\resources\app\node_modules\event-kit\lib\emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (C:\Users\Landon Abney\AppData\Local\atom\app-1.19.0-beta3\resources\app\node_modules\event-kit\lib\emitter.js:141:34)
    at PaneContainer.didAddPaneItem (C:\Users\Landon Abney\AppData\Local\atom\app-1.19.0-beta3\resources\app\src\pane-container.js:270:24)
    at PaneContainer.didAddPane (C:\Users\Landon Abney\AppData\Local\atom\app-1.19.0-beta3\resources\app\src\pane-container.js:242:18)
    at Pane.module.exports.Pane.setContainer (C:\Users\Landon Abney\AppData\Local\atom\app-1.19.0-beta3\resources\app\src\pane.js:162:32)
    at PaneAxis.module.exports.PaneAxis.addChild (C:\Users\Landon Abney\AppData\Local\atom\app-1.19.0-beta3\resources\app\src\pane-axis.js:154:19)
    at PaneAxis.module.exports.PaneAxis.insertChildAfter (C:\Users\Landon Abney\AppData\Local\atom\app-1.19.0-beta3\resources\app\src\pane-axis.js:225:25)
    at Pane.module.exports.Pane.split (C:\Users\Landon Abney\AppData\Local\atom\app-1.19.0-beta3\resources\app\src\pane.js:1004:29)
    at Pane.module.exports.Pane.splitRight (C:\Users\Landon Abney\AppData\Local\atom\app-1.19.0-beta3\resources\app\src\pane.js:964:25)
    at TabBarView.module.exports.TabBarView.splitTab (C:\Users\Landon Abney\AppData\Local\atom\app-1.19.0-beta3\resources\app\node_modules\tabs\lib\tab-bar-view.js:379:37)
    at Object.TabBarView.addElementCommands.tabs:split-right (C:\Users\Landon Abney\AppData\Local\atom\app-1.19.0-beta3\resources\app\node_modules\tabs\lib\tab-bar-view.js:137:32)
    at HTMLUListElement.commandsWithPropagationStopped.(anonymous function) (C:\Users\Landon Abney\AppData\Local\atom\app-1.19.0-beta3\resources\app\node_modules\tabs\lib\tab-bar-view.js:83:42)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\Landon Abney\AppData\Local\atom\app-1.19.0-beta3\resources\app\src\command-registry.js:265:35)
    at CommandRegistry.handleCommandEvent (C:\Users\Landon Abney\AppData\Local\atom\app-1.19.0-beta3\resources\app\src\command-registry.js:3:65)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (C:\Users\Landon Abney\AppData\Local\atom\app-1.19.0-beta3\resources\app\src\command-registry.js:166:25)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchContextMenuCommand (C:\Users\Landon Abney\AppData\Local\atom\app-1.19.0-beta3\resources\app\src\atom-environment.js:1344:34)
    at EventEmitter.outerCallback (C:\Users\Landon Abney\AppData\Local\atom\app-1.19.0-beta3\resources\app\src\application-delegate.js:347:31)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

While debugging this I noticed that the `textEditorElement` in the `StableAdapter` has a `isConnected` property which is initially false (when this bug is triggerable), but is `true` for TextEditors that are fully initialized.

I'm not sure of the best way to handle this though...

Note that https://github.com/atom-minimap/minimap/issues/608 is likely the same issue.

**Comment by Arcanemagus** [comment]
This _might_ be fixed by https://github.com/atom/atom/pull/15051.
